repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:

      # Проверяет наличие переноса строки в конце всех текстовых файлов.
      - id: end-of-file-fixer

      # Предупреждает о добавлении больших файлов в Git.
      - id: check-added-large-files

      # Предупреждает о сохранении файлов с UTF-8 BOM.
      - id: check-byte-order-marker

      # Предотвращает сохранение приватных ключей.
      - id: detect-private-key

      # Проверяет, что файлы, которые мы собираемся сохранять, как минимум валидный Python.
      - id: check-ast

  - repo: local
    hooks:

      # Автоматического изменения порядка импортов.
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: [--settings-path=pyproject.toml]

      # Форматирование кода. Работает.
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--config=pyproject.toml]

      # Линтер.
      -  id: flake8
         name: flake8
         entry: flake8
         language: system
         types: [python]
         args: [
             "--ignore=E203,W503,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013,ANN001,ANN003,ANN101,FI18,ANN201,ANN204,TAE001,E800",
             # black
                 # E203 whitespace before ':'
                 # W503 line break before binary operator
             # flake8-future-import
                 # FI10 __future__ import "division" missing
                 # FI11 __future__ import "absolute_import" missing
                 # FI12 __future__ import "with_statement" missing
                 # FI13 __future__ import "print_function" missing
                 # FI14 __future__ import "unicode_literals" missing
                 # FI15 __future__ import "generator_stop" missing
                 # FI16 __future__ import "nested_scopes" missing
                 # FI17 __future__ import "generators" missing
                 # FI58 __future__ import "annotations" present
             # flake8-pytest-style
                 # PT013 found incorrect import of pytest, use simple 'import pytest' instead
             "--max-line-length=79",
             "--per-file-ignores=tests/*.py:S101"
             # S101 Use of assert detected
         ]

      # Запуск тестов.
#      - id: tests
#        name: tests
#        entry: docker-compose exec -T drf python manage.py test
#          apps.authorization
#        always_run: true
#        pass_filenames: false
#        language: python
#        verbose: true
