version: "3.9"

services:

  django:
    build: .
    image: custom_django
    container_name: django
    hostname: django
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -o /dev/null -s -w '%{http_code}\n' http://localhost:8000/admin/login/?next=/admin/ || 200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    depends_on:
      postgres_for_tests:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Локальная базы данных для тестов.
  postgres_for_tests:
    image: postgres:latest
    container_name: postgres_for_tests
    hostname: postgres_for_tests
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d testing" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  # Дополнительная база данных.
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
