# Generated by Django 4.2.6 on 2024-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=6,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_email",
            field=models.BooleanField(
                default=False,
                help_text="Если почта подтверждена, то пользователю будут доступны некоторые дополнительные функции.",
                verbose_name="Верифицирована ли почта",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Активная ли учетная запись"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                db_comment="Может ли получить доступ к административной панели",
                default=False,
                help_text="Может ли получить доступ к административной панели",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Псевдоним"
            ),
        ),
    ]
